# Generated by Django 5.1.1 on 2024-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_age_alter_cat_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.AddField(
            model_name='cat',
            name='unknown',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
