# Generated by Django 5.1.1 on 2024-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_remove_cat_name_cat_unknown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='unknown',
        ),
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=64, null='unknown'),
            preserve_default='unknown',
        ),
    ]
