# Generated by Django 5.1.1 on 2024-10-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_remove_cat_unknown_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(default='unknown', max_length=64),
        ),
    ]
