# Generated by Django 5.1.1 on 2024-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_alter_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
