# Generated by Django 5.1.1 on 2024-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_alter_cat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(default='unknown', max_length=64, null=True),
        ),
    ]
