# Generated by Django 5.1.1 on 2024-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_alter_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
