# Generated by Django 5.1.1 on 2024-10-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_alter_cat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cat_id', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cats.breed'),
        ),
    ]
