# Generated by Django 5.1.1 on 2024-10-15 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_cat_avg_rating_alter_rating_cat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user_id', 'cat_id'), name='cat-rating'),
        ),
    ]
