# Generated by Django 5.1.1 on 2024-10-15 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_rating_cat_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='cat-rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'cat'), name='cat-rating'),
        ),
    ]
