# Generated by Django 5.1.1 on 2024-10-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_remove_rating_cat_rating_rename_cat_id_rating_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='avg_rating',
        ),
    ]
