# Generated by Django 5.1.1 on 2024-10-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0015_cat_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='avg_rating',
        ),
    ]
